### ISSUE TITLE
Please delete or rename this

### ISSUE THREAD

**Issue by hannesvdvreken** [php-fig-rectified/fig-rectified-standards#6]
The PHP-FIG consists of a number of people involved in open source (framework) communities who have a vote in these standards. Don't abuse the name of PHP-FIG or PSR to promote a different standard, even if that standard was used by frameworks pre PSR-2. We don't want anyone new to PHP to be confused by a unnecessary high number standards or "rectified" standards.

It doesn't matter that PSR-2 prefers spaces over tabs, or a specific placement of braces. Each of those choices have advantages and disadvantages. If we stick together and keep faith in as less standards as possible, we will end up in a better world with less context switches.

Thanks.

**Comment by dereuromark** [comment]
If you have a better name for it, please suggest one.
Otherwise I don't think it should/could harm "yours" in any way.
This merely displays a valid (and IMO more sane) alternative with the reasonings (deficiencies FIG itself was aware of) behind it attached along with it.

**Comment by burzum** [comment]
> This merely displays a valid (and IMO more sane) alternative with the reasonings (deficiencies FIG itself was aware of) behind it attached along with it.

:+1:

**Comment by ArminVieweg** [comment]
I agree with @hannesvdvreken and I think that this fork of PSR-2 standard is counterproductive from a wide point of view.

I would also prefer to indent my code with tabs... but this discussion is just about personal preferences, like this whole fork IMO. For example, I don't think that a new line before opening brace (`{`) is inconsistent. A class or a method is something different than an if-condition or foreach loop.

What you did in other context: Do you know DIN A4? An international standard of paper formats. This specific one is 21x29,7cm large... what? 29,7cm?! What an odd number... Lets create a new DIN A4-R standard which uses 21x30cm, which is much easier to remember... Well, luckly nobody had this idea...

Just my 50 cents.

**Comment by burzum** [comment]
I disagree. Mostly because PSR is obviously a political decision and not decided based on technical arguments. Otherwise tabs would have won over spaces. But people like to stick to their historical legacy and habits and picked spaces over tabs.

Another indicator that my guess about the political decision is right, is that now Yoda-Conditions were made  optional. [Which doesn't make much sense](http://www.dereuromark.de/2015/10/15/avoid-yoda-conditions/). While tabs vs spaces won't hurt the code and is a personal thing, Yoda-Conditions *can* lead to unwanted things.

PSR-R :+1:

**Comment by ArminVieweg** [comment]
I guess these "Yoda-Conditions", funny word-creation, btw. ^^ are existing because of the shortterm to check a negative value like `if (!$isValid)`. Here the assumption is standing in the front (`$isValid == false`). That would be consequent, actually. But I agree, that it is stupid. And declaring a variable inside of an if, is also a no go! I would complain that in every review.

**Comment by hannesvdvreken** [comment]
@ArminVieweg Thanks. I gave up arguing, though.

**Comment by dereuromark** [comment]
> For example, I don't think that a new line before opening brace ({) is inconsistent

So you don't find it inconsistent, that only sometimes there is a newline before it?

    public function foo(...) 
    {
    }

but then all of the sudden

    public function foo(
        ...
    ) {
    }

The latter would actually make sense with consistently no newline before it (which this PSR-2-R actually does^^). It's not thought through, but built by already existing and inferior styles mixed together in a wild vote, not accepting the idea that actually changing the existing styles might make more sense in the long run.

Either way, if you are so sure, then it shouldn't hurt that some people have another opinion :)

**Comment by ArminVieweg** [comment]
https://github.com/php-fig-rectified/fig-rectified-standards/pull/7 ;)
